### PR TITLE
Add coverage test

### LINKED ISSUE #21: Add coverage test for forcetorque plugin

### PR DESCRIPTION
**Pull request by lucapa17**
- Fix #21

### CODE REVIEW

**Comment by lucapa17** [comment]
A few considerations:
- sometimes macos test fails, like windows did. Maybe should we fix it together with #31 ?
- the coverage test shows that we don't use [yarp::dev::IAnalogSensor](https://www.yarp.it//v3.5/classyarp_1_1dev_1_1IAnalogSensor.html#details) interface and its methods that we implemented taking inspiration from [gazebo-yarp-plugins](https://github.com/robotology/gazebo-yarp-plugins/tree/master/plugins/forcetorque). Indeed we use only [yarp::dev::ISixAxisForceTorqueSensors](https://www.yarp.it//v3.5/classyarp_1_1dev_1_1ISixAxisForceTorqueSensors.html) . Should we remove or keep it?
- there are other lines of code that are not covered, such as the error handling ones. We don't know if we should try to cover also them

**Comment by traversaro** [comment]
Good job! I really like that you did not modified anything in the CMake files to add coverage support. For what regards IAnalogSensor methods, feel free to remove them, those interfaces are deprecated. For the rest, I think that for this software there is no strict need for 100% line coverage.

**Comment by traversaro** [comment]
Cool, it seems to work! Probably the error "❗ No coverage uploaded for pull request base (main@f498935). [Click here to learn what that means](https://docs.codecov.io/docs/error-reference?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=robotology#section-missing-base-commit)." it is due to the fact that at the moment the base branch does not have coverage information, but that should be solved once we merge this PR.

**Review by traversaro — APPROVED** [review]

**Comment by traversaro** [comment]
@lucapa17 @GiacomoBisio please remember either to cleanup the history of PRs before merging or (easier) merging PRs as squash, otherwise the history of the repo will become really difficult to navigate, thanks!

**Comment by traversaro** [comment]
> @lucapa17 @GiacomoBisio please remember either to cleanup the history of PRs before merging or (easier) merging PRs as squash, otherwise the history of the repo will become really difficult to navigate, thanks!

To prevent errors, at the moment I forced "Squash and merge", if you want to allow merge commits let me know!

**Pull request merged**
